### ISSUE TITLE
Window is not defined on node/bun

### ISSUE THREAD

**Issue by rebyatyonok** [cross-org/jwt#2]
Hello! 
I run the following code with node/bun
```javascript
#!/usr/bin/node

/* eslint no-console: off */
import { existsSync } from 'node:fs'
import { exportPEMKey, generateKeyPair } from '@cross/jwt'

const paths = {
	private: process.env.PRIVATE_KEY_PATH,
	public: process.env.PUBLIC_KEY_PATH
}

;(async () => {
	const isPrivateExists = existsSync(paths.private)
	const isPublicExists = existsSync(paths.public)

	if (isPrivateExists && isPublicExists) {
		console.log('Keys already exist. Skipping')
	}
	else {
		const { privateKey, publicKey } = await generateKeyPair('PS512')
		exportPEMKey(privateKey, paths.private).then(() => {
			console.log('Private key generated')
		})
		exportPEMKey(publicKey, paths.public).then(() => {
			console.log('Public key generated')
		})
	}
})()
```
and receive an error which is kinda makes sense
```
ReferenceError: window is not defined
    at exportPEMKey (file:///<skipped>/node_modules/@cross/jwt/src/cryptokeys.js:102:23)
    at file:///<skipped>/scripts/generate-keys.js:21:3
```

Node version: v22.2.0
Bun version: 1.1.13

Will you accept a PR to fix that?

**Comment by Pinta365** [comment]
Yes, will gladly look at and accept a PR. :)

**Comment by Pinta365** [comment]
@rebyatyonok version **0.4.9** got a fix using the global crypto object.

**Comment by rebyatyonok** [comment]
@Pinta365 Sorry, didn't have time to submit a PR. Thanks a lot!
